Fix error for MySQL 5.7
When trying to copy a user between MySQL 5.7 servers the following error appears:

user.copy: User-defined function threw an exception: 
Traceback (most recent call last):
  File "/root/.mysqlsh/plugins/user/copy.py", line 205, in copy_users_grants
    if len(old_format) > 0:
TypeError: object of type 'NoneType' has no len()
 (ScriptingError)

It is because variable old_format is assigned value only when MySQL version is different than 8.0 and 5.7 (see around line 101 [1]). So read its length later only in this case. With the modification there is no error and `CREATE USER`/`GRANT` statements are properly generated.

[1] ] https://github.com/lefred/mysqlshell-plugins/blob/0bf2a628b40060cd15da3df247fa8a169d18e88c/user/copy.py#L101